# Generated by Django 2.0.3 on 2018-03-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostoStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dal', models.DateField()),
                ('al', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('storage_level', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Costo Storage',
                'verbose_name_plural': 'Costi Storage',
            },
        ),
    ]
