# Generated by Django 2.0.3 on 2018-04-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['ordine'],
            },
        ),
        migrations.AlterField(
            model_name='costostorage',
            name='storage_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.StorageLevel'),
        ),
    ]
