# Generated by Django 2.0.3 on 2018-04-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_servizio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servizio',
            options={'verbose_name_plural': 'Servizi'},
        ),
        migrations.AddField(
            model_name='costostorage',
            name='servizio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Servizio'),
        ),
    ]
